name: "real_estate_lakehouse"
version: "1.0.0"
config-version: 2

profile: "lakehouse_spark"

# Nơi dbt tìm các file model (SQL)
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target" # Nơi dbt lưu các file đã biên dịch
clean-targets:
  - "target"
  - "dbt_packages"

# Create databases before running models
on-run-start:
  - "CREATE DATABASE IF NOT EXISTS bronze"
  - "CREATE DATABASE IF NOT EXISTS silver"
  - "CREATE DATABASE IF NOT EXISTS gold"

# Cấu hình theo kiến trúc Lakehouse chuẩn
models:
  real_estate_lakehouse:
    # Staging models (Silver layer) → bronze database
    staging:
      +materialized: table
      +file_format: delta

    # Marts models (Gold layer) → Use incremental for efficient updates
    marts:
      +materialized: incremental
      +file_format: delta
      +incremental_strategy: merge
