config:
  send_anonymous_usage_stats: False

lakehouse_spark:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-thrift-server
      port: 10000
      schema: gold # Gold layer models ghi vào gold database
      threads: 1
      connect_timeout: 30
      auth: NOSASL
      transport_mode: binary

    # Staging models có thể cần bronze schema
    staging:
      type: spark
      method: thrift
      host: spark-thrift-server
      port: 10000
      schema: bronze # Staging models đọc từ bronze
      threads: 1
      connect_timeout: 30
      auth: NOSASL
      transport_mode: binary
