config:
  send_anonymous_usage_stats: False

lakehouse_spark:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-thrift-server
      port: 10000
      schema: bronze
      threads: 1
      connect_timeout: 30
      auth: NOSASL 
      transport_mode: binary