version: 2
models:
  - name: stg_properties
    description: "Silver layer - Dữ liệu bất động sản đã được làm sạch và chuẩn hóa"
    columns:
      - name: property_id
        description: "ID duy nhất của property (từ list_id)"
        tests:
          - unique
          - not_null

      - name: title
        description: "Tiêu đề tin đăng"

      - name: area
        description: "Diện tích đất (m²), đã loại bỏ dấu phẩy và convert sang double. Có thể NULL nếu listing không có thông tin diện tích."
        # Note: dbt_expectations package tests commented out due to compatibility issues
        # tests:
        #   - dbt_expectations.expect_column_values_to_be_positive:
        #       row_condition: "area IS NOT NULL"

      - name: price_in_billions
        description: "Giá bất động sản (đơn vị: Tỷ VNĐ), đã chuẩn hóa từ 'tỷ' và 'triệu'"
        # tests:
        #   - dbt_expectations.expect_column_values_to_be_positive

      - name: address
        description: "Địa chỉ đầy đủ, đã chuẩn hóa chữ hoa/thường"

      - name: floors
        description: "Tổng số tầng"

      - name: bedrooms
        description: "Số phòng ngủ"

      - name: bathrooms
        description: "Số phòng vệ sinh"

      - name: legal_status
        description: "Tình trạng giấy tờ pháp lý"

      - name: house_direction
        description: "Hướng cửa chính"

      - name: data_quality_flag
        description: "Cờ đánh dấu chất lượng dữ liệu: VALID, INVALID_AREA, MISSING_PRICE, MISSING_ADDRESS"
        tests:
          - not_null
          - accepted_values:
              values:
                ["VALID", "INVALID_AREA", "MISSING_PRICE", "MISSING_ADDRESS"]

      - name: updated_at_ts
        description: "Timestamp file modification từ MinIO"

      - name: created_at
        description: "Timestamp khi record được tạo trong Silver layer"
